### ISSUE TITLE
Question - Performance of Sling Model Mocks

### ISSUE THREAD

**Issue by royteeuwen** [wcm-io/io.wcm.testing.aem-mock#5] opened 2023-02-21 07:34 UTC
We are using AEM Mocks to create our unit tests. This works very well and we are able to test a lot of our requirements. One thing that is currently an issue is the performance though. To give an example of what we notice

If we have a Sling Model with the following impl:

```
class MyModel {
     @ScriptVariable
      private Page currentPage
}
```

And we replace this with the following and register the 4 relevant OSGi services from wcm-io sling models / commons to make @AemObject work:
```
class MyModel {
     @AemObject
     private Page currentPage
}
```

Our performance of the unit tests go divided by 3 (we go from 1 min to complete all to 3 min's for all our tests combined when we switch 15 Page object annotations from ScriptVariable to AemObject). We notice this with every injector (for example also caconfig) that we add to the AemContext. Is there something that can be done about this? At this moment we opt for using @ScriptVariable just to keep the speediness of the unit tests

**Comment by stefanseifert** [comment] 2023-02-22 08:07
this is interesting - especially as it is recommend to use the specific annotations. i did not notice that before, especially not with this large deviation of taken 200% more time then before. are you able to reproduce this in a smaller test project that you can provide for further analysis?
in our project we use @AemObject all over the place, and i never notices such a huge performance problem.

**Comment by royteeuwen** [comment] 2023-02-22 11:43
@stefanseifert  sure, if you want to see the result, try it out with AEM Core Components. I made a branch, if you do `mvn clean install -DcustomInjectors` it will add the AemObjectInjector as a setup callback (without even using it in the models)

https://github.com/adobe/aem-core-wcm-components/compare/main...royteeuwen:feature/show-performance?expand=1

The results for myself without and with the custom injectors:
![Screenshot 2023-02-22 at 11 59 30](https://user-images.githubusercontent.com/4967758/220610434-5ad60a11-9438-4383-82e2-82fae44a44ea.png)

![Screenshot 2023-02-22 at 12 41 47](https://user-images.githubusercontent.com/4967758/220610452-02b4cde2-a2e2-4023-8737-70130d8c581c.png)

**Comment by stefanseifert** [comment] 2023-02-22 13:06
good idea for this test case! - i will take a deeper look

**Comment by royteeuwen** [comment] 2023-03-09 12:31
Any update about progress on this @stefanseifert ? Were you able to reproduce?

**Comment by stefanseifert** [comment] 2023-03-21 18:29
still, it may be there is room for improvement, probably inside the sling models code itself.
i've added a debug output to the `AemObjectInjector.InjectAnnotationProcessor2#createAnnotationProcessor` method and observed it's execution when running just one single test case of the core components project. it got called 120,970 times! it should be called once for each field in each model. even if we assume each model has 20 fields it should not be more then 1,000 times or so? i've not debugged further, but i never expected that high number. the method is also called lots of multiple times on the same fields.

**Comment by stefanseifert** [comment] 2023-03-22 11:45
i found the issue for the remaining 47% performance increase as well, fixed in the same branch:
https://github.com/adobe/aem-core-wcm-components/compare/main...stefanseifert:aem-core-wcm-components:feature/show-performance?expand=1

after debugging into the details i discovered that even if your register the AemObjectInjector+co at the topmost position with afterSetUp, it's still too late, because the models that are auto-detected from classpath (this feature is activated by default, can be deactivated but that is very inconvenient) are registered before the first afterSetUp call. the solution was to use beforeSetUp instead. this works because the services around AemObjectInjector do not have dependencies to other stuff.

i applied the same change to the `WCMIO_SLING` plugin, so this performance improvements should get active automatically once you update the version of this plugin dependencies: https://github.com/wcm-io/io.wcm.testing.wcm-io-mock.sling/pull/4

**Closed** 2023-03-22 11:49 UTC

**Comment by stefanseifert** [comment] 2023-03-24 18:11
the other plugins should not be problematic, as only this one plugin registered a custom sling models injector. it's a problem specific to sling models injectors. so all other plugins should be kept as afterSetUp and do not need a change. i agree it's the easiest solution to register all plugins at the same time for all unit tests.

**Comment by stefanseifert** [comment] 2023-03-24 18:14
ah, you're right - io.wcm.testing.wcm-io-mock.caconfig is the only plugin that also registers a sling model injector. i will think about it and check if it has a similar effect as well (did not see that in my tests).

**Comment by royteeuwen** [comment] 2023-03-24 18:43
Ok! If you find a general approach on how to fix this, I will see on getting this in the acs commons sling models injectors as well!

**Comment by stefanseifert** [comment] 2023-03-27 08:28
i misremembered - it be precise the caconfig-related models injector is registered in https://github.com/apache/sling-org-apache-sling-testing-caconfig-mock-plugin - and this happens only for projects where additionally https://github.com/apache/sling-org-apache-sling-models-caconfig is deployed and present in classpath, which happens probably only in very few places as this is not part of AEM or AEMaaCS by default and hat be added manually (it was not present in my recent testing of the models injection lifecycle performance issue).

i've created https://issues.apache.org/jira/browse/SLING-11811 to cover this as well.

so i'm not aware of any performance-related problem in io.wcm.testing.wcm-io-mock.caconfig
